Blog_API/urls.py
from django.urls import path
from . import views


app_name = 'Blog_API'

urlpatterns = [
    path('', views.BlogList.as_view(), name = 'blog_list'),
    path('create_blog/', views.CreateBlog.as_view(), name = 'create_blog'),
    path('details/<slug:slug>', views.blog_details, name = 'blog_details'),
    path('like/<pk>/', views.like, name = 'liked_post'),
    path('dislike/<pk>/', views.dislike, name = 'disliked_post'),
    path('my-blogs/', views.MyBlog.as_view(), name = 'my_blogs'),
    path('edit-blog/<pk>/', views.UpdateBlog.as_view(), name = 'update_blog'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_API.urls')),
    path('blog/', include('Blog_API.urls')),
    path('', views.index, name = 'index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog_API/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'post_author')
    blog_title = models.CharField(max_length = 264, verbose_name = 'Put a title')
    slug = models.SlugField(max_length = 264, unique = True)
    blog_content = models.TextField(verbose_name = 'What is on your mind?')
    blog_image = models.ImageField(upload_to = 'blog_images', verbose_name = 'Blog Image')
    publish_date = models.DateTimeField(auto_now_add = True)
    update_date = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ['publish_date']

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name = 'blog_comment')
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'user_comment')
    comment = models.TextField(max_length = 255)
    comment_date = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['comment_date']

    def __str__(self):
        return self.comment

class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name = 'blog_like')
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'user_like')

Blog_API/forms.py
from django import forms
from .models import Blog, Comment


class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea, label='Comment:', required = False)
    class Meta:
        model = Comment
        fields = ('comment',)

Blog_API/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, TemplateView, DeleteView
from Blog_API.models import Blog, Comment, Like
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from .forms import CommentForm


class MyBlog(LoginRequiredMixin, TemplateView):
    template_name = 'Blog_API/my_blogs.html'


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'Blog_API/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('Blog_API:blog_details', kwargs = {'slug' : self.object.slug})

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'Blog_API/blog_list.html'
    # queryset = Blog.objects.order_by('publish_date') - setting order


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'Blog_API/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image')

    def form_valid(self, form):
        blog_obj = form.save(commit = False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

def blog_details(request, slug):
    blog = Blog.objects.get(slug = slug)
    comment_form = CommentForm()
    already_liked = Like.objects.filter(blog = blog, user = request.user)
    if already_liked:
        liked = True
    else:
        liked = False

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit = False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('Blog_API:blog_details', kwargs = {'slug' : slug}))

    return render(request, 'Blog_API/blog_details.html', context = {'blog' : blog, 'comment_form' : comment_form, 'liked' : liked})

@login_required
def like(request, pk):
    blog = Blog.objects.get(pk = pk)
    user = request.user
    already_liked = Like.objects.filter(blog = blog, user = user)
    if not already_liked:
        liked_post = Like(blog = blog, user = user)
        liked_post.save()
    return HttpResponseRedirect(reverse('Blog_API:blog_details', kwargs = {'slug' : blog.slug}))

@login_required
def dislike(request, pk):
    blog = Blog.objects.get(pk = pk)
    user = request.user
    already_liked = Like.objects.filter(blog = blog, user = user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('Blog_API:blog_details', kwargs = {'slug' : blog.slug}))

templates/Blog_API/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Blog Details {% endblock %}

{% block body_block %}
<div class="row">
  <div class="col-sm-6">
    <h2>{{ blog.blog_title }}</h2>
    <h4>Posted By: {{ blog.author }}</h4>
    <i><h6>Published on: {{ blog.publish_date }}</h6></i>
    <i><h6>Updated on: {{ blog.update_date }}</h6></i>
    <h6>{{ blog.blog_like.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
  </div>

  <div class="col-sm-6">
    <img src="/media/{{ blog.blog_image }}" width="100%">
  </div>
  {{ blog.blog_content|linebreaks }}
</div>

{% if not liked %}
<a href="{% url 'Blog_API:liked_post' pk=blog.pk %}">
  <i class="fa fa-thumbs-o-up fa-2x"></i>
</a>
{% else %}
<a href="{% url 'Blog_API:disliked_post' pk=blog.pk %}">
  <i class="fa fa-thumbs-o-down fa-2x"></i>
</a>
{% endif %}
<hr>

<div class="row">
  <div class="col-sm-6">
    <h5>Comments:</h5>
    {% for comment in blog.blog_comment.all %}
    <p><a href="#">{{ comment.user }}</a> | <i>{{ comment.comment_date }}</i></p>
    <b>"{{ comment.comment }}"</b><br>
    <hr>
    {% endfor %}
  </div>
  <div class="col-sm-6">
    <form method="post">
      {{ comment_form|crispy }}
      {% csrf_token %}
      <button type="submit" class="btn btn-primary btn-sm">Comment</button>
    </form>
  </div>
</div>
<br><br><br>
{% endblock %}

templates/Blog_API/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %} Home {% endblock %}

{% block body_block %}
  {% for blog in blogs %}
    <h2>{{ blog.blog_title }}</h2>
    <h6><i>{{ blog.publish_date }}</i></h6>
    <div class="row">
      <div class="col-sm-4">
        <img src="/media/{{ blog.blog_image }}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="100%">
      </div>
      <div class="col-sm-8">
            <p>{{ blog.blog_content|range_filter|linebreaks }}</p>
            <a href="{% url 'Blog_API:blog_details' slug=blog.slug %}">Read More</a><br>
<br>
              <span style="float:left;"><b>Posted by:</b> <a href="#">{{ blog.author.username }}</a><br></span>
              <a style="float:right;text-align:right;"><h6>{{ blog.blog_like.count }} Likes | {{ blog.blog_comment.count }} Comments</h6> </a>
<br><hr>
      </div>
    </div>
  {% endfor %}
      <br>
{% endblock %}

templates/Blog_API/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create Blog {% endblock %}

{% block body_block %}
<h2>Write Your Blog Here:</h2>
<form method="post" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <br>
  <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>

{% endblock %}

templates/Blog_API/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Edit Blog {% endblock %}

{% block body_block %}
{% if blog.author == user %}
<form method="post" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-info btn-sm">Update</button>
</form>
{% else %}
<p>You are not allowed to get access to this page</p>
{% endif %}
{% endblock %}

templates/Blog_API/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %} My Blogs {% endblock %}

{% block body_block %}
<center><h1>- Your Blogs -</h1></center>
<hr>
{% for blog in user.post_author.all %}
<h3>{{ blog.blog_title }}</h3>
<h6>{{ blog.publish_date }}</h6>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{ blog.blog_image }}" width="100%">
  </div>
    <div class="col-sm-8">
      <p>{{ blog.blog_content|range_filter|linebreaks }}</p>
      <a href="{% url 'Blog_API:blog_details' slug=blog.slug %}">Read More</a><br>
<br>
      <a href="{% url 'Blog_API:update_blog' pk=blog.pk %}" class="btn btn-warning btn-sm">Edit Your Blog</a>
        <a style="float:right;text-align:right;"><h6>{{ blog.blog_like.count }} Likes | {{ blog.blog_comment.count }} Comments</h6> </a>
<br><hr>
  </div>
</div>
{% endfor %}
{% endblock %}