Blog_API/urls.py
from django.urls import path
from . import views


app_name = 'Blog_API'

urlpatterns = [
    path('', views.BlogList.as_view(), name = 'blog_list'),
    path('create_blog/', views.CreateBlog.as_view(), name = 'create_blog'),
    path('details/<slug:slug>', views.blog_details, name = 'blog_details'),
    path('like/<pk>/', views.like, name = 'liked_post'),
    path('dislike/<pk>/', views.dislike, name = 'disliked_post'),
    path('my-blogs/', views.MyBlog.as_view(), name = 'my_blogs'),
    path('edit-blog/<pk>/', views.UpdateBlog.as_view(), name = 'update_blog'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_API.urls')),
    path('blog/', include('Blog_API.urls')),
    path('', views.index, name = 'index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Login_API/urls.py
from django.urls import path
from . import views


app_name = 'Login_API'

urlpatterns = [
    path('signup/', views.sign_up, name = 'signup'),
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('profile/', views.profile, name = 'profile'),
    path('change_profile/', views.user_change, name = 'user_change'),
    path('password/', views.pass_change, name = 'pass_change'),
    path('change_profile_image/', views.add_profile_pic, name = 'add_profile_pic'),
    path('change_picture/', views.change_profile_pic, name = 'change_profile_pic'),
]

Login_API/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name = 'user_profile', on_delete = models.CASCADE)
    profile_pic = models.ImageField(upload_to = 'profile_pictures')

Login_API/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from Login_API.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label = 'Email Address', required = True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic',]

Login_API/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Login_API.forms import SignUpForm, UserProfileChange, ProfilePic


def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data = request.POST)
        if form.is_valid():
            form.save()
            registered = True
    context = {'form' : form, 'registered' : registered}
    return render(request, 'Login_API/signup.html', context)

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'Login_API/login.html', context = {'form' : form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_API:login'))

@login_required
def profile(request):
    return render(request, 'Login_API/profile.html', context = {})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance = current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance = current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance = current_user)
    return render(request, 'Login_API/change_profile.html', context = {'form' : form})

@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data = request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'Login_API/pass_change.html', context = {'form' : form, 'changed' : changed})

@login_required
def add_profile_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit = False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('Login_API:profile'))
    return render(request, 'Login_API/add_profile_pic.html', context = {'form' : form})

@login_required
def change_profile_pic(request):
    form = ProfilePic(instance = request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance = request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Login_API:profile'))
    return render(request, 'Login_API/add_profile_pic.html', context = {'form' : form})

templates/Login_API/add_profile_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Update Profile Picture Page {% endblock %}

{% block body_block %}
<h2>Add Your Profile Picture</h2>
<form method="post" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <br>
  <button type="submit" class="btn btn-primary btn-sm">Add Picture</button>
</form>
{% endblock %}

templates/Login_API/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Change Profile Details {% endblock %}

{% block body_block %}
<h2>Update Your Profile Details</h2>
<form method="post">
  {{ form|crispy }}
  {% csrf_token %}
  <br>
  <button type="submit" class="btn btn-primary btn-sm">Update</button>
</form>
{% endblock %}

templates/Login_API/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Login Page {% endblock %}

{% block body_block %}
<h2>Log In Your Account</h2>
<form method="post">
  {{ form|crispy }}
  {% csrf_token %}
  <br>
  <button type="submit" class="btn btn-primary btn-sm">Log In</button>
</form>
{% endblock %}

templates/Login_API/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Change Password Page {% endblock %}

{% block body_block %}

{% if changed %}
<div class="alert alert-success">
  Password changed successfully
</div>
{% endif %}

<h2>Change Your Password</h2>
<form method="post">
  {{ form|crispy }}
  {% csrf_token %}
  <br>
  <button type="submit" class="btn btn-primary btn-sm">Change</button>
</form>
{% endblock %}

templates/Login_API/profile.html
{% extends 'base.html' %}
{% block title %} Profile Page {% endblock %}

{% block body_block %}
<h2>Yur Profile</h2>

{% if user.user_profile %}

  <img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="120px">
  <br><br>
  <a href="{% url 'Login_API:change_profile_pic' %}" class="btn btn-info btn-sm">Update Profile Picture</a>
  <br><br>

{% else %}

  <img src="/media/default.jpg" class="rounded-circle" width="120px">
  <br><br>
  <a href="{% url 'Login_API:add_profile_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
  <br><br>

{% endif %}

<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name: {{ user.first_name }} {{ user.last_name }}</p>
<br>
<a href="{% url 'Login_API:user_change' %}" class="btn btn-warning btn-sm">Update Profile</a>
{% endblock %}

templates/Login_API/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create New Account {% endblock %}

{% block body_block %}
{% if registered %}
  <div class="alert alert-success">
    Account Created Successfully <a href="{% url 'Login_API:login' %}">Log In Here</a>
  </div>
{% else %}
  <h2>Create New Account</h2>
  <form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
  </form>
  <br>
  <p>Already have an account? <a href="{% url 'Login_API:login' %}">Log In Here</a></p>
{% endif %}
{% endblock %}