Blog_API/urls.py
from django.urls import path
from . import views


app_name = 'Blog_API'

urlpatterns = [
    path('', views.BlogList.as_view(), name = 'blog_list'),
    path('create_blog/', views.CreateBlog.as_view(), name = 'create_blog'),
    path('details/<slug:slug>', views.blog_details, name = 'blog_details'),
    path('like/<pk>/', views.like, name = 'liked_post'),
    path('dislike/<pk>/', views.dislike, name = 'disliked_post'),
    path('my-blogs/', views.MyBlog.as_view(), name = 'my_blogs'),
    path('edit-blog/<pk>/', views.UpdateBlog.as_view(), name = 'update_blog'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_API.urls')),
    path('blog/', include('Blog_API.urls')),
    path('', views.index, name = 'index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Login_API/urls.py
from django.urls import path
from . import views


app_name = 'Login_API'

urlpatterns = [
    path('signup/', views.sign_up, name = 'signup'),
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('profile/', views.profile, name = 'profile'),
    path('change_profile/', views.user_change, name = 'user_change'),
    path('password/', views.pass_change, name = 'pass_change'),
    path('change_profile_image/', views.add_profile_pic, name = 'add_profile_pic'),
    path('change_picture/', views.change_profile_pic, name = 'change_profile_pic'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <title>
           {% block title %}
            Blogs Page
           {% endblock %}
    </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Blog_API:create_blog' %}">Write Blog</a>
        </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Login_API:logout' %}">Log Out</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Login_API:profile' %}">Profile</a>
            </li>
        {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Login_API:signup' %}">Sign Up</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Login_API:login' %}">Log In</a>
            </li>
        {% endif %}
      </ul>
          {% if user.is_authenticated %}
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">{{ user.username }}</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'Login_API:profile' %}">Your Profile</a>
          <a class="dropdown-item" href="{% url 'Blog_API:my_blogs' %}">My Blogs</a>
          <a class="dropdown-item" href="{% url 'Login_API:logout' %}">Log Out</a>
        </div>
      </div>
          {% endif %}
    </nav>

    <div class="container" style="padding-top:20px">
      {% block body_block %}

      {% endblock %}
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>